// M0RX Doc Generator - morxdoc
use std::env;
use std::fs;
use std::process;

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        print_help();
        process::exit(0);
    }

    match args[1].as_str() {
        "generate" | "gen" => {
            let path = args.get(2).map(|s| s.as_str()).unwrap_or(".");
            generate_docs(path);
        }
        "version" | "--version" => {
            println!("morxdoc v0.1.0");
        }
        "help" | "--help" => {
            print_help();
        }
        _ => {
            generate_docs(&args[1]);
        }
    }
}

fn generate_docs(path: &str) {
    println!("morxdoc: Generating docs for '{}'...", path);
    let doc = r#"<!DOCTYPE html>
<html>
<head>
<title>M0RX Documentation</title>
<style>
body { font-family: monospace; background: #0d1117; color: #c9d1d9; padding: 20px; }
h1 { color: #58a6ff; }
h2 { color: #79c0ff; border-bottom: 1px solid #30363d; }
.fn { color: #d2a8ff; }
.type { color: #79c0ff; }
.comment { color: #8b949e; }
</style>
</head>
<body>
<h1>M0RX Language Documentation v0.1.0</h1>
<h2>Standard Library</h2>
<p class="comment">Auto-generated by morxdoc</p>
<h2>Core Functions</h2>
<p><span class="fn">showln</span>(value: any) -> nil</p>
<p><span class="fn">show</span>(value: any) -> nil</p>
<p><span class="fn">ask</span>(prompt: str) -> str</p>
<h2>Math Functions</h2>
<p><span class="fn">absolute</span>(n: dbl) -> dbl</p>
<p><span class="fn">root</span>(n: dbl) -> dbl</p>
<p><span class="fn">power</span>(base: dbl, exp: dbl) -> dbl</p>
</body>
</html>"#;
    fs::write("docs/api.html", doc).ok();
    println!("morxdoc: Generated docs/api.html");
    println!("morxdoc: Documentation complete!");
}

fn print_help() {
    println!("morxdoc - M0RX Doc Generator v0.1.0");
    println!("Usage:");
    println!("  morxdoc gen <path>   Generate docs");
    println!("  morxdoc version      Show version");
}
